version: 2
jobs:
  build:
    working_directory: ~/html
    machine:
        image: ubuntu-2204:2023.04.2
    branches:
        ignore:
          - develop
    steps:
      - checkout

      - run:
          name: Prepare and start containers and verify it's working
          command: |
            chmod 777 var/elasticsearch-data
            make start-test

      - run:
          name: Show framework version and additional info, php & composer version
          command: |
            make info

      - run:
          name: Run unit/functional tests
          command: |
            make phpunit

      - run:
          name: Report code coverage
          command: |
            make report-code-coverage

      - run:
          name: Check coding standard & CodeSniffer
          command: |
            make ecs
            make phpcs

      - run:
          name: Run PHPStan
          command: |
            make phpstan

      - run:
          name: Run PHPInsights
          command: |
            make phpinsights

      - run:
          name: Run PHP Mess Detector
          command: |
            make phpmd

      - run:
          name: Run PHP copy past detector
          command: |
            make phpcpd

      - store_artifacts:
          path: reports

      - store_test_results:
          path: reports
