name: Import images from Nasa Api

on:
    push:
        branches:
            - master
            - develop
    pull_request:
        branches:
            - master
            - develop
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Build the docker images
              run: make build
            - name: Start the docker images
              run: make start
            - name: Check running containers
              run: docker ps -a
            - name: Run test suite
              run: make phpunit
            - name: Archive coverage data for Qodana
              uses: actions/upload-artifact@v3
              with:
                  name: php-coverage-data
                  path: reports/clover.xml
            - name: Run coding standard
              run: make ecs
            - name: Run codeSniffer
              run: make phpcs
            - name: Run PHPStan
              run: make phpstan
            - name: Run PHPInsights
              run: make phpinsights
            - name: Run php mess detector
              run: make phpmd
            - name: Run php copy past detector
              run: make phpcpd
            - name: Stop the docker images
              run: make stop
